import {
    ComponentBase,
    VantComponent,
    VantEvent,
    VantTouchEvent,
    VantEventHandler,
    VantTouchEventHandler,
    TouchPositionDetail,
    VantBaseExternalClassName,
    VantBaseLoadingExternalClassName,
    WechatOpenType,
    VantOpenTypeProps,
    VantOpenTypeCamelCaseProps,
    VantOpenTypeEvents,
} from 'vant-weapp-typings';

export {
    ComponentBase,
    VantComponent,
    VantEvent,
    VantTouchEvent,
    VantEventHandler,
    VantTouchEventHandler,
    TouchPositionDetail,
    VantBaseExternalClassName,
    VantBaseLoadingExternalClassName,
    WechatOpenType,
    VantOpenTypeProps,
    VantOpenTypeCamelCaseProps,
    VantOpenTypeEvents,
};
