name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Create GitHub release
              uses: Roang-zero1/github-create-release-action@master
              with:
                  version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    base-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - run: pnpm install

            - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

            - run: pnpm run publish --filter vant-weapp-typings
              env:
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

    react-deploy:
        runs-on: ubuntu-latest
        needs: [base-deploy]
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - run: pnpm install

            - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

            - run: pnpm run publish --filter react-vant-weapp-typings
              env:
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
