name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Create GitHub release
              uses: Roang-zero1/github-create-release-action@master
              with:
                  version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Git Checkout
              uses: actions/checkout@v2
              with:
                  ref: master

            #安装node环境
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: '12'

            - name: Set Dependencies Cache
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: '**/node_modules/**/*'
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              uses: borales/actions-yarn@v2.3.0
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              with:
                  cmd: install

            - name: Build
              run: npm run build

            - name: Set .npmrc file
              run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

            - name: Publish
              run: npm publish
